---
- name: Run NGINX proxy container
  docker_container:
    name: nginx_proxy
    image: alunaxia/tp-devops-httpd
    networks:
      - name: myapp_network
    ports:
      - "80:80"
    state: started
    restart_policy: unless-stopped
