name: CI devops 2024

on:
  # Trigger on push to main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Job for testing the backend
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.5.0  # Checkout the repository code

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Set the JDK version to 17 (Temurin)

      - name: Build and test with Maven
        run: mvn clean verify
        working-directory: simple-api  # Adjust this if your pom.xml is in a different directory

  # Job for building and pushing Docker images
  build-and-push-docker-image:
    needs: test-backend  # This job will only run if test-backend passes
    runs-on: ubuntu-22.04
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Build and push the backend Docker image
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api  # Directory containing the backend Dockerfile
          file: ./simple-api/Dockerfile  # Path to the backend Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-simple-api:latest  # Correct tag format

      # Build and push the database Docker image
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database  # Directory containing the database Dockerfile
          file: ./database/Dockerfile  # Path to the database Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-database:latest  # Correct tag format

      # Build and push the HTTP server Docker image
      - name: Build image and push http-server
        uses: docker/build-push-action@v3
        with:
          context: ./http-server  # Directory containing the http-server Dockerfile
          file: ./http-server/Dockerfile  # Path to the http-server Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-http-server:latest  # Correct tag format
