name: CI devops 2024
on:
  # To begin, you want to launch this job in main and develop
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      # Checkout your GitHub code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Sets up JDK 17

      # Build and test with Maven
      - name: Build and test with Maven
        run: mvn clean verify  # You can customize this command based on your build needs
