name: CI devops 2024

on:
  # Trigger on push to main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build and test with Maven, including SonarCloud analysis
      - name: Build and test with Maven and SonarCloud
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=Applications-of-Big-Data-Assignement-1 \
            -Dsonar.organization=alunaxia \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            --file simple-api/pom.xml  # Corrected path to pom.xml, no need for extra cd command
        working-directory: .  # Running from the root directory

  build-and-push-docker-image:
    needs: test-backend  # This job will only run if test-backend passes
    runs-on: ubuntu-22.04
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Build and push backend image
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api
          file: ./simple-api/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Build and push database image
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database
          file: ./database/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Build and push httpd image
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./http-server
          file: ./http-server/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Login to DockerHub
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
