build-and-push-docker-image:
  needs: test-backend  # This job will only run if test-backend passes
  runs-on: ubuntu-22.04
  steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2.5.0

    # Build and push backend image
    - name: Build image and push backend
      uses: docker/build-push-action@v3
      with:
        context: ./simple-api  # The directory containing Dockerfile for the backend
        file: ./simple-api/Dockerfile  # Specify the Dockerfile location
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest  # Correct tag format

    # Build and push database image
    - name: Build image and push database
      uses: docker/build-push-action@v3
      with:
        context: ./database  # The directory containing Dockerfile for the database
        file: ./database/Dockerfile  # Specify the Dockerfile location
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest  # Correct tag format

    # Build and push httpd image (you need to have a Dockerfile for httpd)
    - name: Build image and push httpd
      uses: docker/build-push-action@v3
      with:
        context: ./httpd  # Adjust if you have another directory for httpd Dockerfile
        file: ./httpd/Dockerfile  # Specify the Dockerfile location
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest  # Correct tag format
